#!/bin/bash
pkill mplayer
pkill flite
pkill vlc
pkill mpg123
chroot /root/OpenWrtAI /bin/bash VLC.sh 'playlist.m3u --random '
sleep 2
chroot /root/OpenWrtAI /bin/bash MPLAYER.sh http://127.0.0.2:9090/stream '-af channels=4:4:0:2:0:0:1:3:1:1' 

