#!/usr/bin/env python3
import openai
import os
import sys

# settings and keys
openai.api_key = "api key"
model_engine = "text-davinci-002"
language = 'en'
###########
 
# define variables


def chatgpt_response(prompt):
    # send the converted audio text to chatgpt
    response = openai.Completion.create(
        engine=model_engine,
        prompt=prompt,
        max_tokens=1024,
        n=1,
        temperature=0.7,
    )
    return response


            
def main():
    # run the program
    filepath = open("/tmp/openai.dat","r")  
    prompt = filepath.read()

    #prompt = sys.argv[1]

    print(f"This is the prompt being sent to OpenAI " + prompt)
    
    responses = chatgpt_response(prompt)
    message = responses.choices[0].text
    print(message)
    f = open("/tmp/openai.text", "w")
    f.write(message)
    f.close()

if __name__ == "__main__":
    main()

