#!/bin/bash
pkill vlc
pkill mplayer
pkill flite
pkill mpg123
station=$(cat station.tmp)

#chroot /root/OpenWrtAI /bin/bash VLC.sh $station
#sleep 2
#chroot /root/OpenWrtAI /bin/bash MPLAYER.sh http://127.0.0.1:9090/stream '-af channels=4:2:0:2:1:3'

chroot /root/OpenWrtAI /bin/bash MPLAYER.sh $station  '-af channels=4:4:0:2:0:0:1:3:1:1'

